version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: polosalud
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3316:3306' 
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql

  app:
    build: .
    container_name: springboot
    ports:
      - '8090:8080' 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/polosalud
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - springboot-mysql
    volumes:
      - app-data:/app/uploads

volumes:
  mysql-data:
  app-data:

networks:
  springboot-mysql:
    driver: bridge
